---
title: "Reporting using quarto"
subtitle: "Reproducibility has never been easier"
institute: "ARCA initiative: Unlocking Psychological Expertise for Academic and Business Success"
author: "Ottavia M. Epifania"
format: 
  html:
    self-contained: true
    toc: true
    toc-location: left
---

Reproducible reports integrate the code used for data analysis with the document that presents the findings, this enabling a continous flow between the analytical process and its interpretation.

While `R`Markdown undoubtely opened the way to this process, `quarto` represents the next generation, as it is even easier to use than `R`Markdown and includes new features, making the reporting process more accessible. 

This course provides an introduction to `quarto` and its basic features, along with a presentation on how to exploit it functionalities to create polished, professional outputs with embedded code chunks.

Some of the topics covered within this seminar are:

- Executable code chunks 
- Tables, charts, and references seamlessly.
- Reports and papers
- Presentation, posters & so much more
